### ISSUE TITLE
Shutdown is not working, it`s displaying the shutdown process but does not halt the system.

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/emonpi#3]
Looking at this.

**Comment by jlark** [comment]
@Basazababo I've found the problem

`
INFO:emonPiLCD:main lcd_string2: 5..4..3..2..1..
Traceback (most recent call last):
  File "emonPiLCD.py", line 534, in <module>
    shutdown()
  File "emonPiLCD.py", line 299, in shutdown
    subprocess.call(['/home/debian/gprsAndEmonInstall/switch_off_gsm_module.py'])
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1259, in _execute_child
    raise child_exception
**OSError: [Errno 13] Permission denied**
root@emonpi:/home/debian/emonpi/lcd# vi switch_off_gsm_module.py
root@emonpi:/home/debian/emonpi/lcd# python switch_off_gsm_module.py
/usr/bin/poff: No pppd is running.  None stopped.
root@emonpi:/home/debian/emonpi/lcd# ls
README.md     gprs_signal.py   i2c_lib.pyc  lcddriver.py              testing
emonPiLCD     gprs_signal.pyc  install      lcddriver.pyc
emonPiLCD.py  i2c_lib.py       lcd_test.py  switch_off_gsm_module.py
root@emonpi:/home/debian/emonpi/lcd# ls -la
total 76
drwxr-xr-x 3 root root  4096 Mar  1 22:14 .
drwxr-xr-x 8 root root  4096 Apr 20  2016 ..
-rw-r--r-- 1 root root   782 Mar  1 20:57 README.md
-rwxr-xr-x 1 root root  1580 Apr 20  2016 emonPiLCD
-rwxr-xr-x 1 root root 17066 Apr 20  2016 emonPiLCD.py
-rw-r--r-- 1 root root  1779 Apr 20  2016 gprs_signal.py
-rw-r--r-- 1 root root  1615 Apr 20  2016 gprs_signal.pyc
-rwxr-xr-x 1 root root   836 Mar  1 20:57 i2c_lib.py
-rw-r--r-- 1 root root  1805 Apr 20  2016 i2c_lib.pyc
-rwxr-xr-x 1 root root  2930 Mar  1 20:57 install
-rwxr-xr-x 1 root root   418 Mar  1 20:57 lcd_test.py
-rwxr-xr-x 1 root root  2688 Mar  1 20:57 lcddriver.py
-rw-r--r-- 1 root root  3288 Apr 20  2016 lcddriver.pyc
**-rw-r--r-- 1 root root   294 Apr 20  2016 switch_off_gsm_module.py**
drwxr-xr-x 2 root root  4096 Mar  1 20:57 testing

*_root@emonpi:/home/debian/emonpi/lcd# chmod +x switch_off_gsm_module.py
*_
to run a program straight from command line it requires to have the +x permission. This was missing from the switch_off_gsm_module command.

Can you make sure this is fixed in the deployment?

**Comment by jlark** [comment]
Actually nevermind I'm merging the code form switch_off_gsm_module.py with gprs_signal.py
